apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: employee-dir
type: Opaque
stringData:
  mongo-uri: "mongodb://mongo-0.mongo-svc.employee-dir.svc.cluster.local:27017/employeedb"
